### PR TITLE
[#177] Fix task IDs falsely updating

### LINKED ISSUE #177: [bug] Re-running same pipeline on same files glitches out task progress
Unexpected behavior when running a directory pipeline while it is already active.

Screenshot 2024-09-26 at 12 21 16 AM

The first run stalls.

Should disable pipelines that are currently being run and thus, aqueducts that direct to those pipelines.

### PR DESCRIPTION
**Pull request by Jkwok0714**
AvoidIDConflicts

Resolves #177

### CODE REVIEW

File: h-util-ui/client/src/components/TaskList/TaskListener.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
+import { SpawnedTask } from '@shared/common.types';
+import { getIpcRenderer } from '@utils/helpers';
+import throttle from 'lodash/throttle';
+
+class TaskListener {
```
Comment (Jkwok0714) [inline h-util-ui/client/src/components/TaskList/TaskListener.ts:5]: May transition this out so the component doesn't do listening, but for now, the issue was on the back end using the same reference to the ID.
